sylius_grid:
    templates:
        action:
            setono_callout_default: "@SetonoSyliusCalloutPlugin/admin/grid/action/setono_callout_default.html.twig"
    grids:
        setono_sylius_callout_admin_callout:
            driver:
                options:
                    class: "%setono_sylius_callout.model.callout.class%"
            sorting:
                priority: asc
            limits: [100, 250, 500, 1000]
            fields:
                code:
                    type: string
                    label: setono_sylius_callout.ui.code
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
                    sortable: ~
                enabled:
                    type: twig
                    label: setono_sylius_callout.ui.enabled
                    sortable: ~
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
                priority:
                    type: twig
                    label: setono_sylius_callout.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
            filters:
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
                date:
                    type: date
                    label: sylius.ui.date
                    options:
                        field: endsAt
                        inclusive_to: true
            actions:
                main:
                    create:
                        type: create
                    assign:
                        type: setono_callout_default
                        label: setono_sylius_callout.ui.action.assign
                        options:
                            icon: refresh
                            link:
                                route: setono_sylius_callout_admin_callout_assign
                item:
                    update:
                        type: update
                    delete:
                        type: delete
